export const Config = {
    VERSION: process.env.REACT_APP_VERSION,
    LOCATIONS_API_URL: process.env.REACT_APP_LOCATIONS_API_URL,
    WORDPRESS_BASE_URL: process.env.REACT_APP_WORDPRESS_BASE_URL,
    WORDPRESS_ENV_PARAM: process.env.REACT_APP_WORDPRESS_ENV_PARAM,
    MAIN_API_URL: process.env.REACT_APP_MAIN_API_URL,
    ENVIRONMENT: process.env.REACT_APP_ENVIRONMENT,
};

