export const Config = {
    COOKIE_PATH: process.env.REACT_APP_COOKIE_PATH,
    VERSION: process.env.REACT_APP_VERSION,
    LOCATIONS_API_URL: process.env.REACT_APP_LOCATIONS_API_URL,
    WORDPRESS_BASE_URL: process.env.REACT_APP_WORDPRESS_BASE_URL,
    WORDPRESS_ENV_PARAM: process.env.REACT_APP_WORDPRESS_ENV_PARAM,
    MANAGE_USERS_API_URL: process.env.REACT_APP_MANAGE_USERS_API_URL,
    ENVIRONMENT: process.env.REACT_APP_ENVIRONMENT,
    LEGACY_API_URL: process.env.REACT_APP_LEGACY_API_URL,
};

